
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  dobHash: 'dobHash',
  dob: 'dob',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MediaScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tmdbId: 'tmdbId',
  imdbId: 'imdbId',
  title: 'title',
  originalTitle: 'originalTitle',
  type: 'type',
  description: 'description',
  posterPath: 'posterPath',
  backdropPath: 'backdropPath',
  releaseDate: 'releaseDate',
  runtime: 'runtime',
  totalSeasons: 'totalSeasons',
  totalEpisodes: 'totalEpisodes',
  currentSeason: 'currentSeason',
  currentEpisode: 'currentEpisode',
  watchedEpisodes: 'watchedEpisodes',
  progressPercentage: 'progressPercentage',
  imdbRating: 'imdbRating',
  imdbVoteCount: 'imdbVoteCount',
  imdbRatingUpdatedAt: 'imdbRatingUpdatedAt',
  status: 'status',
  myRating: 'myRating',
  myReview: 'myReview',
  isFavorite: 'isFavorite',
  notes: 'notes',
  watchedAt: 'watchedAt',
  rewatchCount: 'rewatchCount',
  director: 'director',
  cast: 'cast',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GenreScalarFieldEnum = {
  id: 'id',
  name: 'name',
  tmdbId: 'tmdbId'
};

exports.Prisma.MediaGenreScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  genreId: 'genreId'
};

exports.Prisma.LanguageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code'
};

exports.Prisma.MediaLanguageScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  languageId: 'languageId',
  type: 'type'
};

exports.Prisma.StreamingPlatformScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  logoUrl: 'logoUrl',
  color: 'color',
  isDefault: 'isDefault',
  createdAt: 'createdAt'
};

exports.Prisma.MediaStreamingPlatformScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  platformId: 'platformId'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  platformId: 'platformId',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  color: 'color',
  createdAt: 'createdAt'
};

exports.Prisma.MediaTagScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  tagId: 'tagId'
};

exports.Prisma.CollectionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  description: 'description',
  coverPath: 'coverPath',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CollectionMediaScalarFieldEnum = {
  id: 'id',
  collectionId: 'collectionId',
  mediaId: 'mediaId',
  order: 'order'
};

exports.Prisma.SeasonScalarFieldEnum = {
  id: 'id',
  mediaId: 'mediaId',
  seasonNumber: 'seasonNumber',
  name: 'name',
  overview: 'overview',
  episodeCount: 'episodeCount',
  airDate: 'airDate',
  posterPath: 'posterPath'
};

exports.Prisma.EpisodeScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  episodeNumber: 'episodeNumber',
  name: 'name',
  overview: 'overview',
  airDate: 'airDate',
  runtime: 'runtime',
  stillPath: 'stillPath',
  isWatched: 'isWatched',
  watchedAt: 'watchedAt'
};

exports.Prisma.WatchHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  mediaId: 'mediaId',
  episodeId: 'episodeId',
  watchedAt: 'watchedAt',
  notes: 'notes'
};

exports.Prisma.AppSettingsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  theme: 'theme',
  defaultView: 'defaultView',
  defaultSort: 'defaultSort',
  defaultFilter: 'defaultFilter'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.MediaType = exports.$Enums.MediaType = {
  MOVIE: 'MOVIE',
  SERIES: 'SERIES'
};

exports.WatchStatus = exports.$Enums.WatchStatus = {
  UNASSIGNED: 'UNASSIGNED',
  WANT_TO_WATCH: 'WANT_TO_WATCH',
  WATCHING: 'WATCHING',
  WATCHED: 'WATCHED',
  ON_HOLD: 'ON_HOLD',
  DROPPED: 'DROPPED'
};

exports.LanguageType = exports.$Enums.LanguageType = {
  AUDIO: 'AUDIO',
  SUBTITLE: 'SUBTITLE'
};

exports.Prisma.ModelName = {
  User: 'User',
  Media: 'Media',
  Genre: 'Genre',
  MediaGenre: 'MediaGenre',
  Language: 'Language',
  MediaLanguage: 'MediaLanguage',
  StreamingPlatform: 'StreamingPlatform',
  MediaStreamingPlatform: 'MediaStreamingPlatform',
  Subscription: 'Subscription',
  Tag: 'Tag',
  MediaTag: 'MediaTag',
  Collection: 'Collection',
  CollectionMedia: 'CollectionMedia',
  Season: 'Season',
  Episode: 'Episode',
  WatchHistory: 'WatchHistory',
  AppSettings: 'AppSettings'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
